# Generated by Django 2.1.2 on 2018-12-29 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_match_id', models.IntegerField()),
                ('status', models.CharField(choices=[('SH', 'SCHEDULED'), ('LI', 'LIVE'), ('IP', 'IN_PLAY'), ('PA', 'PAUSED'), ('FN', 'FINISHED'), ('PP', 'POSTPONED'), ('SS', 'SUSPENDED'), ('CN', 'CANCELED')], max_length=2)),
                ('match_day', models.IntegerField()),
                ('match_date_time', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awayTeam', to='teams.Team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeTeam', to='teams.Team')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.League')),
            ],
        ),
    ]
