# Generated by Django 2.1.2 on 2018-12-30 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='ace_link',
            field=models.BooleanField(default=False),
        ),
    ]
