# Generated by Django 2.2.7 on 2020-01-04 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='goals_scored_away_team',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='goals_scored_home_team',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='penalty_goals_away_team',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='penalty_goals_home_team',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.CharField(choices=[('HO', 'Home Team'), ('AT', 'Away Team'), ('DW', 'Draw')], default='', max_length=2),
        ),
    ]
