# Generated by Django 2.1.2 on 2019-02-10 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_match_ace_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('SH', 'Scheduled'), ('LI', 'Live'), ('IP', 'In Play'), ('PA', 'Paused'), ('FN', 'Finished'), ('PP', 'Postponed'), ('SS', 'Suspended'), ('CN', 'Canceled')], max_length=2),
        ),
    ]
