# Generated by Django 2.2.7 on 2020-01-26 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_auto_20200103_2115'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='match',
            table='match',
        ),
    ]
