# Generated by Django 2.2.7 on 2019-11-28 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0001_leagues-migrations'),
        ('teams', '0002_team_league'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='league',
        ),
        migrations.AddField(
            model_name='team',
            name='league',
            field=models.ManyToManyField(null=True, to='leagues.League'),
        ),
    ]
