# Generated by Django 2.1.2 on 2018-12-14 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20181213_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='api_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
