# Generated by Django 2.2.7 on 2019-11-28 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_auto_20191128_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='league',
            field=models.ManyToManyField(to='leagues.League'),
        ),
    ]
