# Generated by Django 2.1.2 on 2019-02-24 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_auto_20190216_0954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team_logo',
            name='logo',
        ),
        migrations.AddField(
            model_name='team_logo',
            name='logo_48x48',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='team_logo',
            name='logo_96x96',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
