# Generated by Django 2.1.2 on 2019-03-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_auto_20190224_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='team_logo',
            name='logo_48x48_url',
            field=models.CharField(max_length=2083, null=True),
        ),
        migrations.AddField(
            model_name='team_logo',
            name='logo_96x96_url',
            field=models.CharField(max_length=2083, null=True),
        ),
    ]
