# Generated by Django 2.1.2 on 2018-12-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_team_tla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='team',
            name='venue',
            field=models.CharField(max_length=100),
        ),
    ]
