# Generated by Django 2.1.2 on 2018-12-15 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_auto_20181215_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='league',
        ),
    ]
