# Generated by Django 2.2.7 on 2020-01-29 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_delete_match'),
        ('teams', '0006_auto_20200126_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team_logo',
            name='team',
        ),
        migrations.RemoveField(
            model_name='teams_in_league',
            name='league',
        ),
        migrations.RemoveField(
            model_name='teams_in_league',
            name='team',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.DeleteModel(
            name='Team_Logo',
        ),
        migrations.DeleteModel(
            name='Teams_in_League',
        ),
    ]
