# Generated by Django 2.1.2 on 2018-12-15 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_teams_in_league'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='crest',
            field=models.CharField(max_length=2083, null=True),
        ),
    ]
