# Generated by Django 2.1.2 on 2018-12-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_auto_20181215_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='club_colors',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='short_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='tla',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='venue',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
