# Generated by Django 2.2.7 on 2019-12-09 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_squashed_0010_remove_user_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useravatar',
            old_name='avatar_height',
            new_name='height',
        ),
        migrations.RenameField(
            model_name='useravatar',
            old_name='avatar_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='useravatar',
            old_name='avatar_width',
            new_name='width',
        ),
        migrations.AddField(
            model_name='useravatar',
            name='image_mode',
            field=models.CharField(default='RGB', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useravatar',
            name='size',
            field=models.CharField(default=(125, 141), max_length=10),
            preserve_default=False,
        ),
    ]
