# Generated by Django 2.2.7 on 2019-12-12 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAvatar',
        ),
    ]
