# Generated by Django 2.2.7 on 2019-12-12 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191209_1614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useravatar',
            old_name='avatar',
            new_name='avatar_bytes',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='NULL', upload_to=''),
            preserve_default=False,
        ),
    ]
