# Generated by Django 2.2.7 on 2019-12-15 02:22

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191212_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(upload_to=django.core.files.storage.FileSystemStorage('./users/media')),
        ),
    ]
