# Generated by Django 2.2.7 on 2019-12-12 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191211_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useravatar',
            name='size',
        ),
    ]
