# Generated by Django 2.2.7 on 2019-12-15 02:27

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191214_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage('./users/media'), upload_to=''),
        ),
    ]
