# Generated by Django 2.2.7 on 2019-12-17 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20191214_2127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useravatar',
            old_name='avatar_bytes',
            new_name='avatar',
        ),
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
    ]
