# Generated by Django 2.2.7 on 2019-12-12 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_useravatar_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='useravatar',
            name='format',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
