# Generated by Django 2.2.7 on 2019-12-12 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_useravatar_format'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useravatar',
            name='avatar_size',
        ),
    ]
