# Generated by Django 2.2.7 on 2019-12-22 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20191216_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='useravatar',
            name='user_one_to_one',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_one_to_one', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
