# Generated by Django 2.2.7 on 2019-12-22 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_useravatar_user_one_to_one'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useravatar',
            name='user',
        ),
    ]
