# Generated by Django 2.2.7 on 2019-12-23 02:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_useravatar_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useravatar',
            name='user_one_to_one',
        ),
        migrations.AddField(
            model_name='useravatar',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
