# Generated by Django 2.1.2 on 2019-06-16 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lineup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('G', 'Goalkeeper'), ('D', 'Defender'), ('M', 'Midfielder'), ('F', 'Forward'), ('F/M', 'Forward/Midfielder'), ('M/D', 'Midfielder/Defender')], max_length=40)),
                ('player', models.CharField(max_length=40)),
                ('lineup_type', models.CharField(choices=[('H', 'Home'), ('A', 'Away')], max_length=10)),
                ('confirmed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.Match')),
            ],
        ),
    ]
