# Generated by Django 2.2.7 on 2020-01-29 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lineups', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lineup',
        ),
    ]
