# Generated by Django 2.1.2 on 2019-01-14 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0001_initial'),
        ('logs', '0002_rotowirerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='rotowirerequest',
            name='league',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='leagues.League'),
            preserve_default=False,
        ),
    ]
