# Generated by Django 2.1.2 on 2019-01-16 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_rotowirerequest_league'),
    ]

    operations = [
        migrations.AddField(
            model_name='rotowirerequest',
            name='up_to_date',
            field=models.BooleanField(default=False),
        ),
    ]
