# Generated by Django 2.1.2 on 2019-01-16 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_rotowirerequest_up_to_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rotowirerequest',
            name='up_to_date',
        ),
    ]
