# Generated by Django 2.1.2 on 2018-11-04 01:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streamer', models.CharField(default=None, max_length=100)),
                ('link', models.CharField(default=None, max_length=100)),
                ('linkScore', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='game',
            old_name='url',
            new_name='postUrl',
        ),
        migrations.AddField(
            model_name='game',
            name='dateTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='links',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Game'),
        ),
    ]
