# Generated by Django 2.1.2 on 2018-11-10 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='aceLink',
            field=models.BooleanField(default=False),
        ),
    ]
