# Generated by Django 2.1.2 on 2019-06-16 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streamer', models.CharField(default='', max_length=100)),
                ('link', models.CharField(default=None, max_length=100)),
                ('linkScore', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScannedMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.CharField(max_length=100)),
                ('postUrl', models.CharField(default='https://reddit.com/soccerstreams', max_length=2083)),
                ('time', models.CharField(max_length=14)),
                ('aceLink', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StreamableMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.Match')),
                ('scanned_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streamablematches.ScannedMatch')),
            ],
        ),
        migrations.AddField(
            model_name='links',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streamablematches.ScannedMatch'),
        ),
    ]
