# Generated by Django 2.2.7 on 2020-01-26 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streamablematches', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Links',
            new_name='Link',
        ),
        migrations.AlterModelTable(
            name='link',
            table='link',
        ),
        migrations.AlterModelTable(
            name='scannedmatch',
            table='scanned_match',
        ),
        migrations.AlterModelTable(
            name='streamablematch',
            table='streamable_match',
        ),
    ]
