# Generated by Django 2.2.7 on 2020-01-27 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streamablematches', '0002_auto_20200126_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueCopy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=30)),
                ('api_id', models.IntegerField(null=True)),
                ('tracked', models.BooleanField(default=False)),
                ('current_match_day', models.IntegerField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'league_copy',
            },
        ),
        migrations.CreateModel(
            name='TeamCopy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField()),
                ('name', models.CharField(max_length=60)),
                ('short_name', models.CharField(max_length=30, null=True)),
                ('tla', models.CharField(max_length=10, null=True)),
                ('venue', models.CharField(max_length=100, null=True)),
                ('club_colors', models.CharField(max_length=30, null=True)),
                ('crest', models.CharField(max_length=2083, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('leagues', models.ManyToManyField(to='streamablematches.LeagueCopy')),
            ],
            options={
                'db_table': 'team_copy',
            },
        ),
        migrations.CreateModel(
            name='TeamsInLeagueCopy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streamablematches.LeagueCopy')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streamablematches.TeamCopy')),
            ],
            options={
                'db_table': 'teams_in_league_copy',
            },
        ),
        migrations.CreateModel(
            name='TeamLogoCopy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_48x48', models.ImageField(null=True, upload_to='')),
                ('logo_48x48_url', models.CharField(max_length=2083, null=True)),
                ('logo_96x96', models.ImageField(null=True, upload_to='')),
                ('logo_96x96_url', models.CharField(max_length=2083, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streamablematches.TeamCopy')),
            ],
            options={
                'db_table': 'team_logo_copy',
            },
        ),
        migrations.CreateModel(
            name='MatchCopy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_match_id', models.IntegerField()),
                ('status', models.CharField(choices=[('SH', 'Scheduled'), ('LI', 'Live'), ('IP', 'In Play'), ('PA', 'Paused'), ('FN', 'Finished'), ('PP', 'Postponed'), ('SS', 'Suspended'), ('CN', 'Canceled')], max_length=2)),
                ('match_day', models.IntegerField()),
                ('match_date_time', models.DateTimeField()),
                ('goals_scored_home_team', models.IntegerField(null=True)),
                ('goals_scored_away_team', models.IntegerField(null=True)),
                ('penalty_goals_home_team', models.IntegerField(null=True)),
                ('penalty_goals_away_team', models.IntegerField(null=True)),
                ('winner', models.CharField(choices=[('HO', 'Home Team'), ('AT', 'Away Team'), ('DW', 'Draw')], default='', max_length=2)),
                ('ace_link', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awayTeam', to='streamablematches.TeamCopy')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeTeam', to='streamablematches.TeamCopy')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streamablematches.LeagueCopy')),
            ],
            options={
                'db_table': 'match_copy',
            },
        ),
    ]
