# Generated by Django 2.1.2 on 2019-04-20 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamablematches', '0002_auto_20181230_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='streamer',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
