# Generated by Django 2.1.2 on 2019-04-20 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamablematches', '0003_auto_20190420_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='streamer',
            field=models.CharField(default='', max_length=100),
        ),
    ]
