# Generated by Django 2.2.7 on 2020-01-29 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0002_auto_20200126_1435'),
        ('streamablematches', '0003_leaguecopy_matchcopy_teamcopy_teamlogocopy_teamsinleaguecopy'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('httpStatusCode', models.CharField(max_length=10)),
                ('requestContent', models.TextField(default=None)),
                ('responseContent', models.TextField(default=None)),
                ('endPoint', models.CharField(max_length=2083)),
                ('exception', models.CharField(max_length=253)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'request log',
                'verbose_name_plural': 'request logs',
                'db_table': 'logs_request_log',
            },
        ),
        migrations.CreateModel(
            name='RotowireRequestLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html', models.TextField()),
                ('parsed_count', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.League')),
            ],
            options={
                'verbose_name': 'rotowire request log',
                'verbose_name_plural': 'rotowire request logs',
                'db_table': 'logs_rotowire_request_log',
            },
        ),
        migrations.CreateModel(
            name='LineupCopy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('G', 'Goalkeeper'), ('D', 'Defender'), ('M', 'Midfielder'), ('F', 'Forward'), ('F/M', 'Forward/Midfielder'), ('M/D', 'Midfielder/Defender')], max_length=40)),
                ('player', models.CharField(max_length=40)),
                ('lineup_type', models.CharField(choices=[('H', 'Home'), ('A', 'Away')], max_length=10)),
                ('confirmed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streamablematches.MatchCopy')),
            ],
            options={
                'db_table': 'lineup_copy',
            },
        ),
    ]
