# Generated by Django 2.2.7 on 2020-01-29 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streamablematches', '0004_lineupcopy_requestlog_rotowirerequestlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rotowirerequestlog',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streamablematches.LeagueCopy'),
        ),
    ]
