# Generated by Django 2.2.7 on 2020-01-29 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streamablematches', '0005_auto_20200128_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamablematch',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streamablematches.MatchCopy'),
        ),
    ]
