# Generated by Django 2.2.7 on 2020-01-25 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('leagues', '0001_initial'), ('leagues', '0002_auto_20191128_1513_squashed_0003_auto_20191130_1041'), ('leagues', '0003_league_current_match_day')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('tracked', models.BooleanField(default=False)),
                ('api_id', models.IntegerField(null=True)),
                ('current_match_day', models.IntegerField(null=True)),
            ],
        ),
    ]
