# Generated by Django 2.2.7 on 2019-11-30 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('leagues', '0002_auto_20191128_1513'), ('leagues', '0003_auto_20191130_1041')]

    dependencies = [
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='tracked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='league',
            name='api_id',
            field=models.IntegerField(null=True),
        ),
    ]
