# Generated by Django 2.2.7 on 2020-01-26 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0001_leagues-migrations'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='league',
            table='league',
        ),
    ]
