# Generated by Django 2.2.7 on 2020-01-29 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0002_auto_20200126_1435'),
    ]

    operations = [
        migrations.DeleteModel(
            name='League',
        ),
    ]
