# Generated by Django 2.2.7 on 2020-01-11 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0002_auto_20191128_1513_squashed_0003_auto_20191130_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='current_match_day',
            field=models.IntegerField(null=True),
        ),
    ]
