# Generated by Django 2.2.7 on 2019-11-30 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0002_auto_20191128_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='api_id',
            field=models.IntegerField(null=True),
        ),
    ]
