# Generated by Django 2.1.2 on 2018-12-15 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0003_auto_20181213_2127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams_in_League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.League')),
            ],
        ),
    ]
