# Generated by Django 2.1.2 on 2018-12-15 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0004_teams_in_league'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teams_in_league',
            name='league',
        ),
        migrations.DeleteModel(
            name='Teams_in_League',
        ),
    ]
